# Generated by Django 3.0.10 on 2023-09-12 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('about', models.TextField()),
                ('photo', models.ImageField(upload_to='images')),
                ('datetime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
